### ISSUE TITLE
Microsoft Edge support

### ISSUE THREAD

**Issue by anewuser** [Narno/Open-New-Tab-After-Current-Tab#14]
This extension works on Microsoft Edge. You can submit it to https://microsoftedge.microsoft.com/

**Comment by Narno** [comment]
![image](https://user-images.githubusercontent.com/80580/121059229-85a91b80-c7c1-11eb-83e4-27e2f4e7abf0.png)

**Comment by anewuser** [comment]
Thank you. 

https://microsoftedge.microsoft.com/addons/detail/open-new-tab-after-curren/deebimacbjlpdcfbpacpckoccjnojacb
