### ISSUE TITLE
chrome update just broke it

### ISSUE THREAD

**Issue by Githubaccountforrandomshit** [Narno/Open-New-Tab-After-Current-Tab#23]
it doesnt work anymore after recent chrome update

**Comment by Narno** [comment]
Yep, it seems `chrome.tabs.onActivated.addListener` event is not working anymore (see https://www.reddit.com/r/chrome_extensions/comments/no7igm/chrometabsonactivatedaddlistener_not_working/).

I'm trying to make a quick fix.

**Comment by Narno** [comment]
It should be fixed with the last version: try to quit Chrome and relaunch it.

**Comment by Githubaccountforrandomshit** [comment]
Thank you so much!07.06.2021, 16:16, "Arnaud Ligny" ***@***.***>:
It should be fixed with the last version (0.4.0): try to quit Chrome and relaunch it.
