### ISSUE TITLE
first tab open is missed by the extension due to background page persistant false in my pc

### ISSUE THREAD

**Issue by sktguha** [Narno/Open-New-Tab-After-Current-Tab#3]
So in my laptop the first tab goes to the usual position at the end. this probably happens because the background page wakes up on the first tab . subsequent new tab opens work fine. so for myself I have made background persistent true and loaded the extension in dev mode.

**Comment by Narno** [comment]
Hello @sktguha, good catch!

I will try your tricks in a next release.

Thank you!
