### ISSUE TITLE
Minor issue: Extension logo invisible in dark mode

### ISSUE THREAD

**Issue by solidifier** [Narno/Open-New-Tab-After-Current-Tab#31]
The current logo is black with transparent background. This makes it seem invisible in dark mode.
You could add a white circle behind the black tabs to make it work in dark or light mode.
Happy to fix it for you.

**Comment by solidifier** [comment]
I've done a new version of the logo here:

https://thelab-my.sharepoint.com/:f:/g/personal/david_thelab_com_au/Epsses6bI1xOsmPyRRd8tzABGZeP7VCdvmpBSHecMPhJLg?e=RdXK0p

I also gave the + tab a bright blue background.. If you'd rather it was just white, let me know and I'll remove it.

**Comment by Narno** [comment]
Hello @solidifier, thank you for your contribution.

The issue is fixed by the PR #32.
