### ISSUE TITLE
Add a shortcut option

### ISSUE THREAD

**Issue by theme1256** [Narno/Open-New-Tab-After-Current-Tab#6]
I would love it, if you could modify the code, so that it didn't override the default behaviour, but instead was a shortcut that you could modify.

This way you have the best of both worlds, where you can open a tab next to the current and at the end.

**Comment by pbakes** [comment]
@theme1256 I think I'm looking for the same thing. Making the new tab button function as it behaves by default, so only the default keyboard shortcut activates the extension? That would make more sense to me.
