### ISSUE TITLE
Sometimes tabs open at the very end

### ISSUE THREAD

**Issue by artquest** [Narno/Open-New-Tab-After-Current-Tab#7]
Sometimes tabs open at the very end.
Chrome 79.0.3945.79.

**Comment by artquest** [comment]
Now it happens almost every time if I try to open a new tab after some time. In other words almost every first new tab opened after a short time (about a minute) open at the end. The second and subsequent tabs opened immediately after the first one do open next to current.

**Comment by Narno** [comment]
Hello @artquest, thanks for your feedback.

I think it's because the background script is not persistent: in case of inactivity, the extension is unloaded so the current tab id is lost.

I will try to turn the persistence on in a next release.

**Comment by Narno** [comment]
See #3.
